
services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    depends_on:
      redis:
        condition: service_healthy

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=gestaopedidos
      - RABBITMQ_DEFAULT_PASS=gestaopedidos
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  catalog.api:
    build:
      context: ./src/Catalog.API
      dockerfile: Dockerfile
    container_name: catalog-api
    ports:
      - "5269:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - "Redis__InstanceName=catalog:"
    depends_on:
      redis:
        condition: service_healthy

  gestao-pedidos.api:
    build:
      context: ./src
      dockerfile: GestaoPedidos.API/Dockerfile
    container_name: gestao-pedidos-api
    ports:
      - "5245:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080 
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=gestaopedidos
      - RabbitMq__Password=gestaopedidos
      - CatalogApi__BaseUrl=http://catalog.api:8080
    depends_on:
      catalog.api:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  gestaopedidos.notificacoes:
    build:
      context: ./src
      dockerfile: GestaoPedidos.Notificacoes/Dockerfile
    container_name: gestaopedidos-notificacoes
    environment:
      - RabbitMq__Host=rabbitmq
      - RabbitMq__Port=5672
      - RabbitMq__Username=gestaopedidos
      - RabbitMq__Password=gestaopedidos
    depends_on:
      rabbitmq:
        condition: service_healthy
      gestao-pedidos.api:
        condition: service_started
      

  api.gateway:
    build:
      context: ./src/ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "5173:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080
    depends_on:
      - catalog.api
      - gestao-pedidos.api
